server:
  port: 9000
  
spring:
  application:
    name: testtelegrambot
    
bot:
  username: SaubulTestTelegramBot
  token: 5279326899:AAEJtRhXCurEeKk1pTHY0Swz6t-Ef8yp_Fk
  
cbr:
  url: https://cbr.ru/DailyInfoWebServ/DailyInfo.asmx